

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'add.py'
- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world